<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_CSL_MAIN" Id="{f7c0fb49-0a9a-4d93-8227-9668f0bcf9c2}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_CSL_MAIN
VAR_INPUT
	bEnable		:	BOOL;
END_VAR
VAR_IN_OUT
	stIn		:	ST_CSL_In;
	st_Params	: 	ST_CSL_Params;
	stOut		:	ST_CSL_Out;
END_VAR
VAR_OUTPUT
END_VAR
VAR
	bInitialized : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_CSL_MAIN">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>