<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_HMI" Id="{2a92276f-68aa-42a1-8ada-c02f33716a1b}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_HMI
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR

VAR_IN_OUT
	st_HMI_In		:	ST_CSL_In;
	st_HMI_Params	: 	ST_CSL_Params;
	st_HMI_Out		: 	ST_CSL_Out;	
	st_HMI_Hmi		: 	ST_CSL_Hmi;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_HMI">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>